import { spawn } from 'node:child_process';
import { lstat, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const interval = Number(process.env.BACKUP_INTERVAL_SECONDS ?? '86400');
const retain = Number(process.env.BACKUP_RETAIN_COUNT ?? '14');
const output = process.env.BACKUP_OUTPUT_DIRECTORY ?? '/backups';
const secrets = process.env.DRM_SECRET_DIR ?? '/recovery-secrets';
if (!Number.isSafeInteger(interval) || interval < 3600 || interval > 604800 ||
    !Number.isSafeInteger(retain) || retain < 2 || retain > 365 || !process.env.BACKUP_DATABASE_URL) {
  throw new Error('Invalid Docker backup interval, retention, or database configuration');
}
let stopping = false;
let child: ReturnType<typeof spawn> | undefined;
let timer: ReturnType<typeof setTimeout> | undefined;
const stop = () => { stopping = true; if (timer) clearTimeout(timer); child?.kill('SIGTERM'); };
process.once('SIGTERM', stop); process.once('SIGINT', stop);

async function backup(): Promise<void> {
  const filename = `standalone-${new Date().toISOString().replaceAll(':', '-')}.drmbackup`;
  child = spawn(process.execPath, ['--experimental-strip-types', 'scripts/standalone-backup.ts', 'create', join(output, filename), secrets],
    { stdio: ['ignore', 'inherit', 'inherit'] });
  const active = child;
  try {
    await new Promise<void>((resolveJob, reject) => {
      active.once('error', reject);
      active.once('close', (code) => code === 0 ? resolveJob() : reject(new Error('Backup failed')));
    });
    await writeFile('/tmp/backup-state.json', JSON.stringify({ lastSuccess: Date.now() }), { mode: 0o600 });
    // Retain only files generated by this scheduler, and only after a successful backup.
    const names = (await readdir(output)).filter((name) => /^standalone-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}\.\d{3}Z\.drmbackup$/.test(name)).sort();
    for (const name of names.slice(0, Math.max(0, names.length - retain))) {
      if ((await lstat(join(output, name))).isFile()) await rm(join(output, name));
    }
  } finally { child = undefined; }
}
async function cycle(): Promise<void> {
  if (stopping) return;
  let next = interval * 1000;
  try { await backup(); }
  catch {
    process.stderr.write(JSON.stringify({ event: 'backup.job_failed' }) + '\n');
    next = Math.min(next, 300_000);
  }
  if (!stopping) timer = setTimeout(() => { void cycle(); }, next);
}
void cycle();
